#!/bin/bash

# run the python script with the request command and the command passed as an argument
echo ""
read -p "~ " command 
echo ""

# echo "Running command: $command"

# store the output command generated by the python script as a string
output=$(python command_generator.py request "$command")

# print the output of the python script
echo "Command: ➜" $output


run_command () {
    echo ""
    echo "Run command? (y/Y) or (n/N)"
    read -p "~ " run
    if [ $run == "y" ] || [ $run == "Y" ]; then
        echo ""
        echo "Running command: $output"
        echo ""
        eval $output
    fi
}

# make a function called paste_command that will paste the command into the terminal

paste_command () {
    echo ""
    echo "Copy to Clipboard? (y/Y) or (n/N)"
    read -p "➜ " paste
    if [ $paste == "y" ] || [ $paste == "Y" ]; then
        # echo ""
        # echo "Pasting command: $output"
        # echo ""
        echo $output | tr -d '\n' | pbcopy
    else
        echo ""
    fi
}

# paste_command
run_command





